/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import datasplitter.GerarCenario;
import estruturas.NoLabel;
import estruturas.Rede;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author charl
 */
public class JanelaConfig extends javax.swing.JFrame {

    private Rede rede;
    private Integer contador;

    /**
     * Creates new form JanelaConfig
     *
     * @param r
     */
    public JanelaConfig(Rede r) {
        // Criar um JPanel com GridLayout
        this.rede = r;
        this.contador = 1;

        initComponents();

        JPanel exibirPanel = new JPanel(new GridLayout(rede.getNumeroDeNos() + 1, 1));

        Double porcentagem = 100.0 / rede.getNumeroDeNos();

        // Adicionar labels às linhas
        for (int i = 0; i < rede.getNumeroDeNos(); i++) {
            //No no = new No("Nó " + i, porcentagem, true, true, true, true, true, true);
            NoLabel noLabel = new NoLabel("Nó " + i, porcentagem);

            this.rede.getListaDeNos().add(noLabel);

            noLabel.print();
            
            TelaNoLabels telaNoLabels = new TelaNoLabels(noLabel);
            exibirPanel.add(telaNoLabels);
        }

        // Criar um JButton
        JButton buttonGerarNos = new JButton("Gerar Rede");

        // Adicionar um ActionListener ao JButton
        buttonGerarNos.addActionListener((ActionEvent e) -> {
            try {
                // Código a ser executado quando o botão for clicado
                gerarRede();
            } catch (IOException ex) {
                System.out.println(ex);
            }
        });

        // Adicionar o JButton ao JPanel
        exibirPanel.add(buttonGerarNos);

        jScrollPane.setViewportView(exibirPanel);

    }

    public void imprimirRede() {
        for (NoLabel noLabel : rede.getListaDeNos()) {
            System.out.println("Nome: " + noLabel.getNome());
            System.out.println("Down: " + noLabel.getDownstairs());
            System.out.println("Up: " + noLabel.getUpstairs());
            System.out.println("Jogg: " + noLabel.getJogging());
            System.out.println("Sitt: " + noLabel.getSitting());
            System.out.println("Stan: " + noLabel.getStanding());
            System.out.println("Walk: " + noLabel.getWalking());
        }
    }

    public void gerarRede() throws IOException {
        GerarCenario gerarCenario = new GerarCenario(rede, contador++);
        gerarCenario.leituraArquivo();
        gerarCenario.divideClasses();
        gerarCenario.gerar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables

    public Rede getRede() {
        return rede;
    }

    public void setRede(Rede rede) {
        this.rede = rede;
    }
}
