/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package telas;

import estruturas.NoLabel;

/**
 *
 * @author charl
 */
public class TelaNoLabels extends javax.swing.JPanel {

    private NoLabel noLabel;

    /**
     * Creates new form TelaNo
     *
     * @param noLabel
     */
    public TelaNoLabels(NoLabel noLabel) {
        initComponents();

        this.noLabel = noLabel;

        jLabelNome.setText(noLabel.getNome());
        jSpinnerDownstairs.setValue(noLabel.getDownstairs());
        jSpinnerUpstairs.setValue(noLabel.getUpstairs());
        jSpinnerSitting.setValue(noLabel.getSitting());
        jSpinnerStanding.setValue(noLabel.getStanding());
        jSpinnerWalking.setValue(noLabel.getWalking());
        jSpinnerJogging.setValue(noLabel.getJogging());
        
        noLabel.print();
    }

    public void atualizaNo() {
        noLabel.setDownstairs((Double) jSpinnerDownstairs.getValue());
        noLabel.setUpstairs((Double) jSpinnerUpstairs.getValue());
        noLabel.setSitting((Double) jSpinnerSitting.getValue());
        noLabel.setStanding((Double) jSpinnerStanding.getValue());
        noLabel.setWalking((Double) jSpinnerWalking.getValue());
        noLabel.setJogging((Double) jSpinnerJogging.getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelDownstairs = new javax.swing.JLabel();
        jSpinnerDownstairs = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabelUpstairs = new javax.swing.JLabel();
        jSpinnerUpstairs = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jLabeSitting = new javax.swing.JLabel();
        jSpinnerSitting = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jLabelStanding = new javax.swing.JLabel();
        jSpinnerStanding = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        jLabelWalking = new javax.swing.JLabel();
        jSpinnerWalking = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabelJogging = new javax.swing.JLabel();
        jSpinnerJogging = new javax.swing.JSpinner();
        jLabelNome = new javax.swing.JLabel();

        jLabelDownstairs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDownstairs.setText("Downstairs");

        jSpinnerDownstairs.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 5.0d));
        jSpinnerDownstairs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerDownstairsStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelDownstairs, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSpinnerDownstairs, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabelDownstairs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerDownstairs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelUpstairs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUpstairs.setText("Upstairs");

        jSpinnerUpstairs.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 5.0d));
        jSpinnerUpstairs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerUpstairsStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelUpstairs, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSpinnerUpstairs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabelUpstairs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerUpstairs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabeSitting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeSitting.setText("Sitting");

        jSpinnerSitting.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 5.0d));
        jSpinnerSitting.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerSittingStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeSitting, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSpinnerSitting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabeSitting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerSitting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelStanding.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStanding.setText("Standing");

        jSpinnerStanding.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 5.0d));
        jSpinnerStanding.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerStandingStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSpinnerStanding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabelStanding, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabelStanding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerStanding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelWalking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWalking.setText("Walking");

        jSpinnerWalking.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 5.0d));
        jSpinnerWalking.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerWalkingStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelWalking, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSpinnerWalking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabelWalking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerWalking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelJogging.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJogging.setText("Jogging");

        jSpinnerJogging.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 5.0d));
        jSpinnerJogging.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerJoggingStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelJogging, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSpinnerJogging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabelJogging)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerJogging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerDownstairsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerDownstairsStateChanged
        // TODO add your handling code here:
        atualizaNo();
        
        System.out.println("1");
    }//GEN-LAST:event_jSpinnerDownstairsStateChanged

    private void jSpinnerUpstairsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerUpstairsStateChanged
        // TODO add your handling code here:
        atualizaNo();
        System.out.println("2");
    }//GEN-LAST:event_jSpinnerUpstairsStateChanged

    private void jSpinnerSittingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerSittingStateChanged
        // TODO add your handling code here:
        atualizaNo();
        System.out.println("3");
    }//GEN-LAST:event_jSpinnerSittingStateChanged

    private void jSpinnerStandingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerStandingStateChanged
        // TODO add your handling code here:
        atualizaNo();
        System.out.println("4");
    }//GEN-LAST:event_jSpinnerStandingStateChanged

    private void jSpinnerWalkingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerWalkingStateChanged
        // TODO add your handling code here:
        atualizaNo();
        System.out.println("5");
    }//GEN-LAST:event_jSpinnerWalkingStateChanged

    private void jSpinnerJoggingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerJoggingStateChanged
        // TODO add your handling code here:
        atualizaNo();
        System.out.println("5");
    }//GEN-LAST:event_jSpinnerJoggingStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeSitting;
    private javax.swing.JLabel jLabelDownstairs;
    private javax.swing.JLabel jLabelJogging;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelStanding;
    private javax.swing.JLabel jLabelUpstairs;
    private javax.swing.JLabel jLabelWalking;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSpinner jSpinnerDownstairs;
    private javax.swing.JSpinner jSpinnerJogging;
    private javax.swing.JSpinner jSpinnerSitting;
    private javax.swing.JSpinner jSpinnerStanding;
    private javax.swing.JSpinner jSpinnerUpstairs;
    private javax.swing.JSpinner jSpinnerWalking;
    // End of variables declaration//GEN-END:variables
}
